#!/bin/bash

# Exit if not running as root
if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi

# Installs
apt update

apt install -y eog evince firefox gedit nautilus

# If nautilus.desktop exists prepend line NoDisplay=true (stop in showing)
if [ -f "/usr/share/applications/nautilus.desktop" ]; then
    sed -i "1s;^;NoDisplay=true\n;" /usr/share/applications/nautilus.desktop
fi

apt install -y network-manager-gnome

# Config Settings / Dconf
