#!/bin/bash

# Exit if not running as root
if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi

# Installs
apt update

apt install -y eog evince firefox gedit nautilus

if [ -f "/usr/share/applications/nautilus.desktop" ]; then 
    echo "NoDisplay=true" >> "/usr/share/applications/nautilus.desktop"
fi

apt install -y network-manager-gnome

# Config Settings / Dconf
