#!/bin/bash

# Exit if not running as root
if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi

# Installs
apt update

# Codecs
apt install -y flac lame vorbis-tools wavpack

# Key applications
apt install -y clementine pavucontrol picard

# Rubyripper
apt install -y cdparanoia ruby
apt install -y cd-discid cdrdao libcdio-utils libgtk2.0-dev sox vorbisgain
gem install rake gtk2 gettext
sudo -u $(logname) git clone https://github.com/bleskodev/rubyripper.git ../rubyripper
cwd=$(pwd)
cd ../rubyripper
sudo -u $(logname) ./configure --enable-lang-all --enable-gtk2 --enable-cli --prefix=/usr
make install
cd $cwd
