#!/bin/bash

# Exit if not running as root
if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi

# Installs
apt update

# Codecs
apt install -y flac lame vorbis-tools wavpack

# Key applications
apt install -y clementine pavucontrol picard

# Rubyripper
# Codecs
